from enum import StrEnum


class SystemRole(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    IT_ADMIN = "IT_ADMIN"
    KNOWLEDGE_ADMIN = "KNOWLEDGE_ADMIN"
    CLINICAL_REVIEWER = "CLINICAL_REVIEWER"
    APOTEKER = "APOTEKER"
    KEPALA_INSTALASI = "KEPALA_INSTALASI"
    KFT = "KFT"
    PMKP = "PMKP"
    DIREKTUR = "DIREKTUR"
    VIEWER = "VIEWER"

